### ISSUE TITLE
Model extension

### ISSUE THREAD

**Issue by bcba25** [Oreobird/Face-Anti-Spoofing#3]
What do you think, if I extend the model by passing rPPG signals as a third input, will it improve accuracy ?

**Comment by Oreobird** [comment]
I think so. Actually there are some papers using rPPG as the input and achieve good result.

**Comment by hxdef2517** [comment]
@Oreobird could you suggest on how to add extra layer ? 
I receive rPPG in a certain format:
rPPG: [[39.61070196 42.81476385 78.65356786]]
shape: (1, 3) 

Do I need to reshape it, pass through MLP or just directly inject in a dense layer and concat?
